accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.authenticate_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
]

contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"
urlpatterns = [
    path("", views.get_name, name="get_name"),
    path("thanks/<str:name>", views.thanks, name="thanks"),
    path("create/", views.create, name="create"),
]

mysite/urls.py
from django.urls import include, path
from mysite.admin import admin_site


urlpatterns = [
    path('admin/', admin_site.urls),
    path('accounts/', include("accounts.urls")),
    path('polls/', include("polls.urls")),
    path('contacts/', include("contacts.urls"))
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

accounts/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models


class Contact(models.Model):
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=240)
    sender = models.EmailField()
    cc_myself = models.BooleanField(null=True, blank=True)

polls/models.py
import datetime 

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField("Texto da questão", max_length=200)
    pub_date = models.DateTimeField("Data da publicação")
    active = models.BooleanField("Ativo", default=True)

    class Meta:
        verbose_name = 'Questão'
        verbose_name_plural = 'Questões'
    
    def __str__(self):
        return f'{self.question_text}'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.PROTECT, verbose_name='Questão')
    choice_text = models.CharField('Descrição',max_length=200)
    votes = models.IntegerField('Votos', default=0)

    def __str__(self):
        return f'Question{self.question.id}: {self.choice_text}'

    class Meta:
        verbose_name = 'Opção'
        verbose_name_plural = 'Opções'

contacts/forms.py
from django import forms

from .models import Contact


class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields="__all__"

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def authenticate_user(request):
    context = {}

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("contacts:create"))
        else:
            context["message"] = "Usuário ou senha inválidos!"
            return render(request, "accounts/login.html", context)
        
    return render(request, "accounts/login.html", context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("accounts:login"))

contacts/views.py
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import ContactForm, NameForm


@permission_required("contacts.add_contact")
def create(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["subject"]
            form.save()
            return HttpResponseRedirect(reverse('contacts:thanks', args=(name, )))
    else:
        form = ContactForm()
    return render(request, "contacts/create.html", {"form": form})


def get_name(request):
    if request.method == "POST":
        form = NameForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['your_name']
            return HttpResponseRedirect(reverse('contacts:thanks', args=(name, )))
    else:
        form = NameForm()

    return render(request, "contacts/name.html", {"form": form})


def thanks(request, name):
    return HttpResponse(f"Congratulations {name}!")

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from polls.models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "Você não escolheu uma opção.",
            },
        )

    selected_choice.votes = F("votes") + 1
    selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

accounts/templates/accounts/login.html
<h1>Login</h1>

{% if message %}
<p style="color: red;">{{ message }}</p>
{% endif %}

<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" id="username">
    <input type="text" name="password" id="password">
    <input type="submit" value="Entrar">
</form>

contacts/templates/contacts/create.html
<a href="{% url 'accounts:login' %}">Sair</a>
<form action="{% url 'contacts:create' %}" method="post" novalidate>
    {% csrf_token %}
    {{form}} 
    <input type="submit" value="Enviar">
</form>

contacts/templates/contacts/name.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>Name</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            background-color: darkcyan;        
        }
    </style>
</head>
<body>
    <form action="{% url 'contacts:get_name' %}" method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
    </form>
</body>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nenhuma enquete foi criada.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Votar novamente?</a>